// ** Fake user data and data type
// =============== Fake Data ============================
export const users = [
  {
    id: 1,
    name: 'admin',
    password: 'admin',
    email: 'admin@vuexy.com',
    image: '/images/avatars/1.png',
    role: 'admin',
    ability: [
      'dashboard',
      'summary',
      'analytics',
      'reports',
      'customers',
      'allcustomers',
      'customersegment',
      'products',
      'allproducts',
      'categories',
      'bulkimport',
      'inventory',
      'metas',
      'tags',
      'offers',
      'allcoupons',
      'customercoupons',
      'orders',
      'allorders',
      'bulkprocessing',
      'transactions',
      'archivedorders',
      'cms',
      'storesetup',
      'style',
      'banners',
      'stories',
      'seo',
      'pages',
      'media',
      'google',
      'facebook',
      'socialprofiles',
      'payments',
      'cashondelivery',
      'razorpay',
      'phonepe',
      'shipping',
      'shippingzones',
      'shippingcharges',
      'pincodes',
      'taxes',
      'taxrate',
      'taxgroup',
      'email',
      'smtp',
      'templates',
      'sendemails',
      'notifications',
      'firebasesetup',
      'smstemplates',
      'sendnotification',
      'sms',
      'smssetup',
      'smstemplates',
      'shippers',
      'delhivery',
      'bluedart',
      'shiprocket',
      'shipdelight'
    ]
  },
  {
    id: 2,
    name: 'support',
    password: 'admin',
    email: 'support@vuexy.com',
    image: '/images/avatars/2.png',
    role: 'support',
    ability: [
      'customers',
      'allcustomers',
      'customersegment',
      'products',
      'allproducts',
      'categories',
      'bulkimport',
      'inventory',
      'metas',
      'tags',
      'offers',
      'allcoupons',
      'customercoupons',
      'orders',
      'allorders',
      'bulkprocessing',
      'transactions',
      'archivedorders'
    ]
  },
  {
    id: 3,
    name: 'marketing',
    password: 'admin',
    email: 'marketing@vuexy.com',
    image: '/images/avatars/3.png',
    role: 'marketing',
    ability: [
      'dashboard',
      'summary',
      'analytics',
      'reports',
      'products',
      'allproducts',
      'categories',
      'bulkimport',
      'inventory',
      'metas',
      'tags',
      'offers',
      'allcoupons',
      'customercoupons',
      'cms',
      'seo',
      'pages',
      'email',
      'templates',
      'sendemails',
      'notifications',
      'firebasesetup',
      'smstemplates',
      'sendnotification',
      'sms',
      'smssetup',
      'smstemplates'
    ]
  },
  {
    id: 4,
    name: 'catalog',
    password: 'admin',
    email: 'catalog@vuexy.com',
    image: '/images/avatars/4.png',
    role: 'catalog',
    ability: [
      'email',
      'products',
      'allproducts',
      'categories',
      'bulkimport',
      'inventory',
      'metas',
      'tags',
      'offers',
      'allcoupons',
      'customercoupons',
      'cms',
      'seo',
      'pages',
      'templates',
      'sendemails',
      'notifications',
      'firebasesetup',
      'smstemplates',
      'sendnotification',
      'sms',
      'smssetup',
      'smstemplates'
    ]
  },
  {
    id: 5,
    name: 'super-admin',
    password: 'admin',
    email: 'superadmin@vuexy.com',
    image: '/images/avatars/5.png',
    role: 'superadmin',
    ability: [
      
      'dashboard',
      'summary',
      'analytics',
      'reports',
      'admin',
      'adminusers',
      'adminroles',
      'customers',
      'allcustomers',
      'customersegment',
      'products',
      'allproducts',
      'categories',
      'bulkimport',
      'inventory',
      'metas',
      'tags',
      'offers',
      'allcoupons',
      'customercoupons',
      'orders',
      'allorders',
      'bulkprocessing',
      'transactions',
      'archivedorders',
      'cms',
      'storesetup',
      'style',
      'banners',
      'stories',
      'seo',
      'pages',
      'media',
      'google',
      'facebook',
      'socialprofiles',
      'payments',
      'cashondelivery',
      'razorpay',
      'phonepe',
      'shipping',
      'shippingzones',
      'shippingcharges',
      'pincodes',
      'taxes',
      'taxrate',
      'taxgroup',
      'email',
      'smtp',
      'templates',
      'sendemails',
      'notifications',
      'firebasesetup',
      'smstemplates',
      'sendnotification',
      'sms',
      'smssetup',
      'smstemplates',
      'shippers',
      'delhivery',
      'bluedart',
      'shiprocket',
      'shipdelight'
    ]
  }
]
